packages:
  - name: importer
    actions:
      - name: importer
        runtime: 'nodejs:20'
        limits:
          timeout: 10000
          memory: 256
          logs: 100
        triggers:
          - name: Run once every 10 minutes
            sourceType: scheduler
            sourceDetails:
              cron: 0/10 * * * *
              withBody: {}
