packages:
  - name: importer
    functions:
      - name: importer
        binary: false
        runtime: 'nodejs:20'
        limits:
          timeout: 10000
          memory: 256
          logs: 100
